"""``scheduler: none`` — run a node's payload directly on the cluster host, as a detached process.

For a workstation or a server you can SSH into that has no batch system. Same interface as
:mod:`flower.hpc.slurm`, so the job executor keeps all its guarantees (write-ahead intent, idempotent
launch, batched polls, typed verdicts):

* **launch**: ``nohup setsid bash job.sh &`` inside the attempt directory, from the login shell of the
  host (``bash -lc``), so the payload sees that machine's own environment (PATH, conda, modules).
  ``setsid`` gives the payload its own process group: cancel signals the whole tree (mpirun, …).
* **job id**: the payload's PID, written by ``job.sh`` itself to ``.flower/owner/id`` (also the
  duplicate guard: a second copy of the same attempt exits with 97 at once).
* **idempotency**: ``mkdir .flower/launched`` is the launch lock. A retried launch after a dropped
  connection re-attaches to the recorded PID instead of starting a second copy.
* **liveness**: ``kill -0 PID`` plus, on Linux, ``/proc/PID/cwd`` == attempt dir (guards PID reuse).
  Dead without ``.flower/ec`` means the process was killed hard or the machine rebooted -> ``lost``.
* **several login nodes behind one address** (SCNet: each ssh connection may land on another node; their home
  filesystem is shared, their processes are not): the payload records its node in ``.flower/host``. A poll from
  another node reads the files (the exit code) but cannot see the process: that is no evidence of its death, so
  it is no miss, and nothing is killed from there. Cancel leaves ``.flower/cancelled``, which a watcher beside
  the payload, on its node, acts on.
* **time limit**: ``resources.time`` (or the node's ``timeout.total``) is enforced with coreutils
  ``timeout``; hitting it leaves ``.flower/timed_out`` and fails with class ``timeout``.

Pattern from Eleforge's ``runners/ssh_machine/runner.py`` (detached PID + exit-code file + LOST
watchdog), aiida ``core.direct``, dpdispatcher ``Shell`` and jobflow-remote's ``shell`` scheduler.
"""
from __future__ import annotations

import re
import shlex

from . import slurm

NAME = "none"
LABEL = "process"
DEFAULT_MIN_POLL = 10.0
DEFAULT_LOST_AFTER = 60.0
START_WAIT_S = 10  # how long the launch call waits for the payload to record its PID

parse_submit = slurm.parse_submit
parse_poll = slurm.parse_poll


def log_names(job_id: str | None) -> tuple[str, str]:
    return "job.out", "job.err"


def retrieve_patterns() -> list[str]:
    return ["job.out", "job.err"]


def validate_resources(resources: dict) -> None:
    time_limit_s(resources)  # raises ValueError on a malformed time; other keys mean nothing without a scheduler


def time_limit_s(resources: dict) -> float | None:
    """``resources.time``: minutes when a number (as for Slurm), else a duration ('2h', '01:30:00')."""
    from ..util import parse_duration
    v = resources.get("time")
    if v is None or v == "" or v is False:
        return None
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return float(v) * 60
    return parse_duration(v)


def render_job_script(*, key: str, job_dir: str, resources: dict, env: dict, prelude: list[str] | str | None,
                      modules: list[str] | None, state_dir: str | None = None,
                      tmpdir: str | None = None) -> str:
    exports = " ".join(f"{k}={shlex.quote(str(v))}" for k, v in sorted(env.items())
                       if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k))
    pre = prelude if isinstance(prelude, list) else ([prelude] if prelude else [])
    mods = [f"module load {m}" for m in (modules or [])]
    limit = time_limit_s(resources)
    if limit:
        secs = max(1, int(round(limit)))
        run = [f"if command -v timeout >/dev/null 2>&1; then timeout -s TERM -k 30 {secs} bash ./user.sh; else bash ./user.sh; fi",
               "ec=$?",
               f'if [ "$ec" = 124 ] || [ "$ec" = 137 ]; then command -v timeout >/dev/null 2>&1 && touch .flower/timed_out; fi']
    else:
        run = ["bash ./user.sh", "ec=$?"]
    lines = [
        "#!/bin/bash",
        f"# {key}",
        "# --- generated by flower (scheduler: none): do not edit (the user payload is user.sh) ---",
        f"FLOWER_JOB_DIR={shlex.quote(job_dir)}",
        'cd "$FLOWER_JOB_DIR" || exit 96',
        # kept across the retries of one start (checkpoints); a rerun or an edit starts a new series
        (f"FLOWER_STATE_DIR={shlex.quote(state_dir)}" if state_dir else 'FLOWER_STATE_DIR="$FLOWER_JOB_DIR/state"')
        + '; mkdir -p "$FLOWER_STATE_DIR"',
        "export FLOWER_STATE_DIR",
        *([] if not tmpdir else [('TMPDIR="$FLOWER_JOB_DIR/tmp"' if tmpdir == "job" else f'TMPDIR="{tmpdir}"')
                                 + '; mkdir -p "$TMPDIR"; export TMPDIR']),
        "mkdir -p .flower",
        # duplicate guard: a second copy of the same attempt exits at once
        "if ! mkdir .flower/owner 2>/dev/null; then",
        '  echo "flower: another process already owns this attempt; exiting" >&2; exit 97; fi',
        'echo "$$" > .flower/owner/id.tmp && mv .flower/owner/id.tmp .flower/owner/id',
        'hostname > .flower/host.tmp 2>/dev/null && mv .flower/host.tmp .flower/host',
        # cancelled before it got going (e.g. a crash window): do not start the payload
        'if [ -e .flower/cancelled ]; then echo 130 > .flower/ec.tmp && mv .flower/ec.tmp .flower/ec; exit 0; fi',
        'date -u +%Y-%m-%dT%H:%M:%SZ > .flower/started',
        # a cancel from a connection that landed on another node only leaves the marker: act on it from here
        "( trap '' TERM; while kill -0 $$ 2>/dev/null; do if [ -e .flower/cancelled ]; then " + _signal("$$", "TERM")
        + "; sleep 10; " + _signal("$$", "KILL") + "; exit 0; fi; sleep 5; done ) >/dev/null 2>&1 < /dev/null &",
        f"export FLOWER_JOB_DIR FLOWER_OUTPUTS=\"$FLOWER_JOB_DIR/outputs.json\" FLOWER_INPUTS=\"$FLOWER_JOB_DIR/inputs.json\" FLOWER_INSIDE_RUN=1 {exports}",
        *mods,
        *pre,
        *run,
        'echo "$ec" > .flower/ec.tmp && mv .flower/ec.tmp .flower/ec',
        'date -u +%Y-%m-%dT%H:%M:%SZ > .flower/ended',
        'exit "$ec"',
    ]
    return "\n".join(lines) + "\n"


def submit_command(job_dir: str, key: str, fingerprint: str, cmds: dict) -> str:
    """One remote call: re-attach if this attempt was already launched, else launch it exactly once."""
    q = shlex.quote
    return f"""set -e
cd {q(job_dir)}
mkdir -p .flower
if [ -s .flower/jobid ]; then echo "EXISTING $(cat .flower/jobid)"; exit 0; fi
if [ -s .flower/owner/id ]; then cp .flower/owner/id .flower/jobid; echo "EXISTING $(cat .flower/jobid)"; exit 0; fi
if ! mkdir .flower/launched 2>/dev/null; then
  i=0; while [ $i -lt {START_WAIT_S * 10} ]; do
    if [ -s .flower/owner/id ]; then cp .flower/owner/id .flower/jobid; echo "EXISTING $(cat .flower/jobid)"; exit 0; fi
    sleep 0.1; i=$((i+1)); done
  echo "launched earlier but no process id was recorded" >&2; exit 75
fi
echo {q(fingerprint)} > .flower/fingerprint
if command -v setsid >/dev/null 2>&1; then L=setsid; else L=; fi
nohup $L bash job.sh > job.out 2> job.err < /dev/null &
i=0; while [ $i -lt {START_WAIT_S * 10} ]; do [ -s .flower/owner/id ] && break; sleep 0.1; i=$((i+1)); done
if [ ! -s .flower/owner/id ]; then echo "the process did not start: $(tail -c 300 job.err 2>/dev/null)" >&2; exit 70; fi
cp .flower/owner/id .flower/jobid
echo "SUBMITTED $(cat .flower/jobid)"
"""


def poll_command(jobs: list[tuple[str, str]], cmds: dict) -> str:
    """Evidence for many processes in one round-trip; @@END marks a complete answer."""
    q = shlex.quote
    parts = ['echo "@@HOST $(hostname 2>/dev/null)"']
    for pid, d in jobs:
        p = q(str(pid))
        parts.append(f"echo '@@EV {pid}'; cd {q(d)} 2>/dev/null && {{ "
                     "printf 'ec=%s\\n' \"$(cat .flower/ec 2>/dev/null)\"; "
                     "[ -s .flower/owner/id ] && printf 'owner=%s\\n' \"$(cat .flower/owner/id)\"; "
                     "[ -s .flower/host ] && printf 'host=%s\\n' \"$(cat .flower/host)\"; "
                     "[ -f .flower/started ] && echo started; [ -f .flower/cancelled ] && echo cancelled; "
                     "[ -f .flower/timed_out ] && echo timed_out; [ -f outputs.json ] && echo outputs; "
                     "L=$(tail -n 5 job.out 2>/dev/null | tr -d '\\r' | grep -v '^[[:space:]]*$' | tail -n 1 | cut -c1-200); "
                     "[ -n \"$L\" ] && printf 'tail=%s\\n' \"$L\"; "
                     f"if kill -0 {p} 2>/dev/null && {{ [ ! -d /proc/{p} ] || [ /proc/{p}/cwd -ef . ]; }}; "
                     "then echo alive; fi; true; } || echo missing_dir")
    parts.append("echo @@END")
    return "\n".join(parts)


def observe(job_id: str, poll: dict) -> dict:
    ev = poll["evidence"].get(job_id, {})
    obs = {"sched": None, "source": "evidence", "ec": ev.get("ec"), "started": bool(ev.get("started")),
           "cancel_marker": bool(ev.get("cancelled")), "has_outputs": bool(ev.get("outputs")),
           "missing_dir": bool(ev.get("missing_dir")), "owner": ev.get("owner"),
           "timed_out": bool(ev.get("timed_out")), "poll_ok": bool(poll.get("complete", True))}
    if obs["ec"] is not None:
        obs["state"], obs["sched"] = "EXITED", "EXITED"
    elif ev.get("alive"):
        obs["state"], obs["sched"] = "RUNNING", "RUNNING"
    elif obs["cancel_marker"]:
        obs["state"], obs["sched"] = "EXITED", "CANCELLED"  # killed by our cancel: TERM leaves no exit code
    elif ev.get("host") and poll.get("host") and ev["host"] != poll["host"]:
        # asked from another node: its processes are not visible from here, only its files
        obs["state"], obs["sched"], obs["source"] = "RUNNING", "RUNNING", "files (another node)"
    else:
        obs["state"] = "UNKNOWN"  # dead without an exit code: counted as a miss, then `lost`
    return obs


def verdict(obs: dict) -> tuple[str, str | None, str, bool]:
    ec = obs.get("ec")
    if obs.get("cancel_marker") and ec in (None, 130, 143):
        return "cancelled", "cancelled", "process cancelled by flower", False
    if ec == 0:
        return "succeeded", None, "exit code 0", False
    if obs.get("timed_out"):
        return "failed", "timeout", "time limit reached (resources.time / timeout.total)", False
    if ec == 97:
        return "failed", "duplicate", "duplicate-launch guard fired: another process owns this attempt", False
    if ec is not None:
        return "failed", "exit_nonzero", f"payload exited with code {ec}", False
    return "failed", "unknown", "process ended without an exit code", True


def _signal(pid: str, sig: str) -> str:
    """Signal the payload's whole *session* (setsid made it the leader): `timeout` and mpirun put their children in
    process groups of their own, which a signal to the leader's group alone never reaches."""
    return (f'pkill -{sig} -s {pid} 2>/dev/null; kill -{sig} -- -{pid} 2>/dev/null || kill -{sig} {pid} 2>/dev/null')


def _here(job_dir: str | None) -> str:
    """True (in the shell) on the node the payload runs on; an attempt that recorded no node is taken as here."""
    if not job_dir:
        return "true"
    h = f"{shlex.quote(job_dir)}/.flower/host"
    return f'{{ [ ! -s {h} ] || [ "$(cat {h})" = "$(hostname 2>/dev/null)" ]; }}'


def cancel_command(job_dir: str | None, job_id: str | None, submit_key: str | None, cmds: dict) -> list[str]:
    """Mark the attempt cancelled, then TERM (and 10 s later KILL) the payload's process session. Over a connection
    that landed on another node only the mark is left; the payload's watcher acts on it."""
    q = shlex.quote
    parts = []
    if job_dir:
        parts.append(f"mkdir -p {q(job_dir)}/.flower && touch {q(job_dir)}/.flower/cancelled")
    pid = f"{q(str(job_id))}" if job_id else (f"\"$(cat {q(job_dir)}/.flower/owner/id 2>/dev/null)\"" if job_dir else "")
    if pid:
        term = _signal('"$P"', "TERM")
        parts.append(f"P={pid}; if [ -n \"$P\" ] && {_here(job_dir)}; then {term}; "
                     f"nohup sh -c \"sleep 10; pkill -KILL -s $P 2>/dev/null; kill -KILL -- -$P 2>/dev/null || "
                     f"kill -KILL $P 2>/dev/null\" >/dev/null 2>&1 < /dev/null & fi; true")
    return parts


def kill_command(job_id: str, cmds: dict, job_dir: str | None = None) -> str:
    p = shlex.quote(str(job_id))
    return f"if {_here(job_dir)}; then pkill -KILL -s {p} 2>/dev/null; kill -KILL -- -{p} 2>/dev/null || kill -KILL {p} 2>/dev/null; fi; true"
