"""Slurm specifics: batch script rendering, the idempotent submit protocol, batched polling, verdicts.

Sources (context/notes/hpc-execution.md §8): Eleforge's submit-key dedupe (the only surveyed system
that closes the crash-between-sbatch-and-record window), dpdispatcher's job-id file, aiida/snakemake
polling (squeue for live jobs, sacct for jobs that left the queue, work-dir evidence files last),
jobflow-remote's "exited, verdict pending" state and typed failure reasons.
"""
from __future__ import annotations

import hashlib
import re
import shlex

from ..rundir import fs_name

NAME = "slurm"
LABEL = "Slurm job"
DEFAULT_MIN_POLL = 30.0
DEFAULT_LOST_AFTER = 600.0

# scheduler state -> flower job state
QUEUED_STATES = {"PENDING", "CONFIGURING", "REQUEUED", "REQUEUE_HOLD", "REQUEUE_FED", "RESV_DEL_HOLD",
                 "SPECIAL_EXIT", "PD", "CF", "RQ", "RH", "RD", "RF", "SE"}
RUNNING_STATES = {"RUNNING", "COMPLETING", "STAGE_OUT", "SUSPENDED", "SIGNALING", "STOPPED", "RESIZING",
                  "R", "CG", "SO", "S", "SI", "ST", "RS"}
TERMINAL_STATES = {"COMPLETED", "FAILED", "CANCELLED", "TIMEOUT", "OUT_OF_MEMORY", "NODE_FAIL", "PREEMPTED",
                   "BOOT_FAIL", "DEADLINE", "REVOKED", "CD", "F", "CA", "TO", "OOM", "NF", "PR", "BF", "DL", "RV"}
SHORT = {"CD": "COMPLETED", "F": "FAILED", "CA": "CANCELLED", "TO": "TIMEOUT", "OOM": "OUT_OF_MEMORY",
         "NF": "NODE_FAIL", "PR": "PREEMPTED", "BF": "BOOT_FAIL", "DL": "DEADLINE", "RV": "REVOKED"}

# typed failure reason, retryable by default?
FAILURE = {
    "TIMEOUT": ("timeout", False), "DEADLINE": ("timeout", False), "OUT_OF_MEMORY": ("oom", False),
    "NODE_FAIL": ("node_fail", True), "BOOT_FAIL": ("node_fail", True), "PREEMPTED": ("preempted", True),
    "FAILED": ("exit_nonzero", False), "REVOKED": ("cancelled_ext", False), "CANCELLED": ("cancelled_ext", False),
}

RESOURCE_FLAGS = {
    "nodes": "--nodes", "ntasks": "--ntasks", "ntasks_per_node": "--ntasks-per-node",
    "cpus_per_task": "--cpus-per-task", "mem": "--mem", "mem_per_cpu": "--mem-per-cpu", "time": "--time",
    "partition": "--partition", "account": "--account", "qos": "--qos", "gpus": "--gpus", "gres": "--gres",
    "constraint": "--constraint", "reservation": "--reservation", "exclude": "--exclude",
}


def base_state(raw: str) -> str:
    s = (raw or "").strip().upper().split()[0] if raw and raw.strip() else ""
    s = s.rstrip("+")
    return SHORT.get(s, s)


def submit_key(run_id: str, node_id: str, attempt: int) -> str:
    h = hashlib.sha256(run_id.encode()).hexdigest()[:8]
    key = f"flower-{h}-{fs_name(node_id)}-a{attempt}"
    return key if len(key) <= 64 else f"flower-{h}-{hashlib.sha256(key.encode()).hexdigest()[:20]}-a{attempt}"


def sbatch_directives(resources: dict) -> list[str]:
    lines = []

    def safe(v) -> str:
        s = str(v)
        if "\n" in s or "\r" in s:
            raise ValueError(f"resource value {s!r} contains a newline")
        return s

    for key, flag in RESOURCE_FLAGS.items():
        v = resources.get(key)
        if v is None or v is False or v == "":
            continue
        if key == "time" and isinstance(v, (int, float)) and not isinstance(v, bool):
            secs = max(1, int(round(float(v) * 60)))  # minutes (possibly fractional) -> H:MM:SS
            v = f"{secs // 3600}:{(secs % 3600) // 60:02d}:{secs % 60:02d}"
        lines.append(f"#SBATCH {flag}={safe(v)}")
    if resources.get("exclusive"):
        lines.append("#SBATCH --exclusive")
    for extra in resources.get("extra") or []:
        if not str(extra).startswith("--"):
            raise ValueError(f"extra sbatch flag {extra!r} must start with --")
        lines.append(f"#SBATCH {safe(extra)}")
    return lines


def render_job_script(*, key: str, job_dir: str, resources: dict, env: dict, prelude: list[str] | str | None,
                      modules: list[str] | None) -> str:
    exports = " ".join(f"{k}={shlex.quote(str(v))}" for k, v in sorted(env.items()) if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k))
    pre = prelude if isinstance(prelude, list) else ([prelude] if prelude else [])
    mods = [f"module load {m}" for m in (modules or [])]
    lines = [
        "#!/bin/bash",
        f"#SBATCH --job-name={key}",
        "#SBATCH --output=slurm-%j.out",
        "#SBATCH --error=slurm-%j.err",
        *sbatch_directives(resources),
        "# --- generated by flower: do not edit (the user payload is user.sh) ---",
        f"FLOWER_JOB_DIR={shlex.quote(job_dir)}",
        'cd "$FLOWER_JOB_DIR" || exit 96',
        "mkdir -p .flower",
        # duplicate guard: a second copy of the same attempt exits at once; a Slurm requeue (same id) proceeds
        'if ! mkdir .flower/owner 2>/dev/null; then',
        '  if [ "$(cat .flower/owner/id 2>/dev/null)" != "${SLURM_JOB_ID:-}" ]; then',
        '    echo "flower: another job already owns this attempt; exiting" >&2; exit 97; fi',
        "fi",
        'echo "${SLURM_JOB_ID:-}" > .flower/owner/id',
        # cancelled while queued (possibly an orphan from a crash window): do not start the payload
        'if [ -e .flower/cancelled ]; then echo 130 > .flower/ec.tmp && mv .flower/ec.tmp .flower/ec; exit 0; fi',
        'date -u +%Y-%m-%dT%H:%M:%SZ > .flower/started',
        f"export FLOWER_JOB_DIR FLOWER_OUTPUTS=\"$FLOWER_JOB_DIR/outputs.json\" FLOWER_INSIDE_RUN=1 {exports}",
        *mods,
        *pre,
        "bash ./user.sh",
        "ec=$?",
        'echo "$ec" > .flower/ec.tmp && mv .flower/ec.tmp .flower/ec',
        'date -u +%Y-%m-%dT%H:%M:%SZ > .flower/ended',
        'exit "$ec"',
    ]
    return "\n".join(lines) + "\n"


def submit_command(job_dir: str, key: str, fingerprint: str, cmds: dict) -> str:
    """One remote call: re-attach if this attempt already has a job, else sbatch exactly once.

    Evidence is checked in order of certainty: the job-id file, the sbatch output that never got renamed
    (crash window), the in-job owner record, then the scheduler by job name. If squeue cannot answer we
    refuse to submit (exit 75, transient) rather than risk a duplicate.
    """
    q = shlex.quote
    squeue, sacct, sbatch = cmds.get("squeue", "squeue"), cmds.get("sacct", "sacct"), cmds.get("sbatch", "sbatch")
    return f"""set -e
cd {q(job_dir)}
mkdir -p .flower
if [ -s .flower/jobid ]; then echo "EXISTING $(cut -d';' -f1 .flower/jobid)"; exit 0; fi
if [ -s .flower/jobid.tmp ] && cut -d';' -f1 .flower/jobid.tmp | grep -Eq '^[0-9]+(_[0-9]+)?$'; then
  mv .flower/jobid.tmp .flower/jobid; echo "EXISTING $(cut -d';' -f1 .flower/jobid)"; exit 0; fi
if [ -s .flower/owner/id ]; then cp .flower/owner/id .flower/jobid; echo "EXISTING $(cat .flower/jobid)"; exit 0; fi
if ! SQ=$({squeue} -h -u "$USER" -t all -o '%i|%j' 2>&1); then echo "squeue unavailable, not submitting: $SQ" >&2; exit 75; fi
J=$(printf '%s\\n' "$SQ" | awk -F'|' -v k={q(key)} '$2==k {{print $1}}' | head -1)
if [ -z "$J" ]; then J=$({sacct} -X -n -P --name={q(key)} -S now-7days -o JobIDRaw 2>/dev/null | head -1 || true); fi
if [ -n "$J" ]; then echo "$J" > .flower/jobid; echo "EXISTING $J"; exit 0; fi
{sbatch} --parsable --job-name={q(key)} --comment={q(fingerprint)} --chdir={q(job_dir)} job.sh > .flower/jobid.tmp
mv .flower/jobid.tmp .flower/jobid
echo "SUBMITTED $(cut -d';' -f1 .flower/jobid)"
"""


def parse_submit(out: str) -> tuple[str, str] | None:
    for line in reversed(out.strip().splitlines()):
        m = re.match(r"^(SUBMITTED|EXISTING)\s+(\d+(?:_\d+)?)\s*$", line.strip())
        if m:
            return m.group(2), m.group(1).lower()
    return None


def poll_command(jobs: list[tuple[str, str]], cmds: dict) -> str:
    """One round-trip for many jobs: squeue (all of the user's jobs), sacct for our ids, evidence files.
    Ends with @@END so a truncated response (connection dropped mid-way) is recognised as a poll error."""
    q = shlex.quote
    ids = ",".join(j for j, _ in jobs if j)
    parts = ["echo @@SQUEUE",
             f"{cmds.get('squeue', 'squeue')} -h -u \"$USER\" -t all -o '%i|%T|%r' 2>&1 || echo @@SQUEUE_ERR"]
    if ids:
        parts += ["echo @@SACCT",
                  f"{cmds.get('sacct', 'sacct')} -X -n -P -j {ids} -o JobIDRaw,State,ExitCode,Elapsed 2>&1 || echo @@SACCT_ERR"]
    for jid, d in jobs:
        parts.append(f"echo '@@EV {jid}'; cd {q(d)} 2>/dev/null && {{ "
                     "printf 'ec=%s\\n' \"$(cat .flower/ec 2>/dev/null)\"; "
                     "[ -s .flower/owner/id ] && printf 'owner=%s\\n' \"$(cat .flower/owner/id)\"; "
                     "[ -f .flower/started ] && echo started; [ -f .flower/cancelled ] && echo cancelled; "
                     "[ -f outputs.json ] && echo outputs; true; } || echo missing_dir")
    parts.append("echo @@END")
    return "\n".join(parts)


def parse_poll(out: str) -> dict:
    """-> {'squeue': {id: (state, reason)}, 'sacct': {id: (state, exit, elapsed)}, 'evidence': {id: {...}},
           'squeue_ok': bool, 'sacct_ok': bool}"""
    res: dict = {"squeue": {}, "sacct": {}, "evidence": {}, "squeue_ok": True, "sacct_ok": True, "complete": False}
    section, cur = None, None
    for line in out.splitlines():
        s = line.strip()
        if s == "@@SQUEUE":
            section = "squeue"
            continue
        if s == "@@SACCT":
            section = "sacct"
            continue
        if s == "@@SQUEUE_ERR":
            res["squeue_ok"] = False
            continue
        if s == "@@SACCT_ERR":
            res["sacct_ok"] = False
            continue
        if s == "@@END":
            res["complete"] = True
            section = None
            continue
        if s.startswith("@@EV "):
            section, cur = "ev", s.split(None, 1)[1]
            res["evidence"][cur] = {}
            continue
        if not s:
            continue
        if section == "squeue":
            parts = s.split("|")
            if len(parts) >= 2:
                res["squeue"][parts[0].strip()] = (base_state(parts[1]), parts[2].strip() if len(parts) > 2 else "")
        elif section == "sacct":
            parts = s.split("|")
            if len(parts) >= 2:
                res["sacct"][parts[0].strip()] = (base_state(parts[1]), parts[2] if len(parts) > 2 else "",
                                                  parts[3] if len(parts) > 3 else "")
        elif section == "ev" and cur:
            ev = res["evidence"][cur]
            if s.startswith("ec="):
                v = s[3:].strip()
                ev["ec"] = int(v) if re.fullmatch(r"-?\d+", v) else None
            elif s.startswith("owner="):
                ev["owner"] = s[6:].strip()
            else:
                ev[s] = True
    return res


def observe(job_id: str, poll: dict) -> dict:
    """Merge the three sources for one job -> {'state': QUEUED|RUNNING|EXITED|UNKNOWN, 'sched': raw, …}."""
    ev = poll["evidence"].get(job_id, {})
    sq = poll["squeue"].get(job_id)
    sa = poll["sacct"].get(job_id)
    obs = {"sched": None, "source": None, "ec": ev.get("ec"), "started": bool(ev.get("started")),
           "cancel_marker": bool(ev.get("cancelled")), "has_outputs": bool(ev.get("outputs")),
           "missing_dir": bool(ev.get("missing_dir")), "owner": ev.get("owner"),
           "poll_ok": bool(poll.get("squeue_ok")) and bool(poll.get("complete", True))}
    if sq:
        st = sq[0]
        obs["sched"], obs["source"] = st, "squeue"
        if st in QUEUED_STATES:
            obs["state"] = "QUEUED"
        elif st in RUNNING_STATES:
            obs["state"] = "RUNNING"
        elif st in TERMINAL_STATES:
            obs["state"] = "EXITED"
        else:
            obs["state"] = "RUNNING" if obs["started"] else "QUEUED"
        if obs["state"] != "EXITED" or not sa:
            if obs["state"] == "EXITED":
                obs["final"] = st
            return obs
    if sa:
        st = sa[0]
        obs["sched"], obs["source"], obs["exit"], obs["elapsed"] = st, "sacct", sa[1], sa[2]
        if st in TERMINAL_STATES:
            obs["state"], obs["final"] = "EXITED", st
        elif st in RUNNING_STATES:
            obs["state"] = "RUNNING"
        else:
            obs["state"] = "QUEUED"
        return obs
    if obs["ec"] is not None:
        obs["state"], obs["source"] = "EXITED", "evidence"
        return obs
    obs["state"] = "UNKNOWN"
    return obs


def verdict(obs: dict) -> tuple[str, str | None, str, bool]:
    """-> (status, error_class, message, retryable) for an EXITED job."""
    ec, final = obs.get("ec"), obs.get("final")
    if obs.get("cancel_marker") and (final in (None, "CANCELLED") or ec in (None, 130)):
        return "cancelled", "cancelled", "job cancelled by flower", False
    if ec == 0 and final not in ("TIMEOUT", "OUT_OF_MEMORY", "NODE_FAIL", "PREEMPTED", "BOOT_FAIL"):
        return "succeeded", None, "exit code 0", False
    if ec is None and str(obs.get("exit") or "").split(":")[0] == "97":
        return "failed", "duplicate", "duplicate-submission guard fired: another job owns this attempt", False
    if final in FAILURE and (ec is None or final != "FAILED"):
        cls, retry = FAILURE[final]
        return "failed", cls, f"Slurm reports {final}" + (f" (exit {obs.get('exit')})" if obs.get("exit") else ""), retry
    if ec is not None and ec != 0:
        return "failed", "exit_nonzero", f"job payload exited with code {ec}", False
    if final == "COMPLETED" and ec is None:
        return "failed", "missing_ec", "Slurm says COMPLETED but the payload never recorded its exit code", True
    return "failed", "unknown", f"job ended in state {final or 'unknown'} without an exit code", True


def log_names(job_id: str | None) -> tuple[str, str]:
    return f"slurm-{job_id}.out", f"slurm-{job_id}.err"


def retrieve_patterns() -> list[str]:
    return ["slurm-*.out", "slurm-*.err"]


def validate_resources(resources: dict) -> None:
    sbatch_directives(resources)  # raises ValueError on newline injection / bad extra flags


def cancel_command(job_dir: str | None, job_id: str | None, submit_key: str | None, cmds: dict) -> list[str]:
    """Mark the attempt cancelled on the cluster and scancel whatever job may exist for it."""
    q = shlex.quote
    sc, sq = cmds.get("scancel", "scancel"), cmds.get("squeue", "squeue")
    parts = []
    if job_dir:
        parts.append(f"mkdir -p {q(job_dir)}/.flower && touch {q(job_dir)}/.flower/cancelled")
    if job_id:
        parts.append(f"{sc} {q(job_id)} 2>&1 || true")
    else:  # crash window: the job may exist although we never recorded its id
        if job_dir:
            parts.append(f"for f in {q(job_dir)}/.flower/jobid {q(job_dir)}/.flower/jobid.tmp "
                         f"{q(job_dir)}/.flower/owner/id; do [ -s \"$f\" ] && {sc} \"$(cut -d';' -f1 \"$f\")\" 2>&1; done; true")
        if submit_key:
            parts.append(f"for j in $({sq} -h -u \"$USER\" -o '%i|%j' 2>/dev/null | awk -F'|' "
                         f"-v k={q(submit_key)} '$2==k {{print $1}}'); do {sc} \"$j\"; done; true")
    return parts


def kill_command(job_id: str, cmds: dict) -> str:
    return f"{cmds.get('scancel', 'scancel')} {shlex.quote(job_id)} >/dev/null 2>&1 || true"
